### PR TITLE
feat: Add options for zoom, height,& width

### PR DESCRIPTION
**Pull request by clburlison**
Idk if you like how it's implemented but it works

### CODE REVIEW

**Comment by clburlison** [comment]
Don't merge. Need to go back and fix the s2 cell functions.

**Comment by ccev** [comment]
Looks good, just needs example config entries. And you don't replace the number in the s2cell functions - that's always L17

**Comment by ccev** [comment]
I'll leave this up for now and try to figure out a nicer solution later. If I can't find one, I'll merge this :) Until then, one can check this out if they're desperate

To make this work I'd also have to change some minor stuff for tileserver and adjust the default configs.

thank you

**Comment by ccev** [comment]
currently working on a nicer solution to this (templates branch) thanks anyway

**Pull request closed without merging**
