### PR TITLE
add geojson support

### PR DESCRIPTION
**Pull request by lenisko**

### CODE REVIEW

**Comment by lenisko** [comment]
Oh crap.. I had some VERY old version :joy:

**Comment by ccev** [comment]
If you rebase against v2 branch, I'll blindly merge it

**Comment by lenisko** [comment]
Done. I'll convert it to v3 soon too. Unless it's not stable?

**Comment by ccev** [comment]
v3 isn't stable yet. i hope for Koji to have some centralized geofence storage that i can use instead

**Comment by lenisko** [comment]
It's set as main branch, hence question. Feel free to merge to v2 then, working on my side.

**Comment by lenisko** [comment]
Hey! if it's not going to be merged to v2 please close. Cleaning gh :)

**Comment by ccev** [comment]
thanks for the reminder. as promised, i'll blindly merge it

**Pull request merged**
